[package]
name = "ward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
regex = "1.10.2"
reqwest = "0.11.22"
tokio = { version = "1.33.0", features = ["full"] }
